### ISSUE TITLE
Generated code includes incorrect/invalid copyright & license notice

### ISSUE THREAD

**Issue by BatmanAoD** [xuri/xgen#12]
The generated Go code includes this notice:

```
// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
```

I am not a lawyer, but it seems improbable to me that this is a valid copyright, because "the xgen authors" did not actually write the generated code (generation based on a schema is not a "creative act"). I'm also not sure the license notice is valid; it would surprise me if code generators can automatically apply their own source code's license to the code they generate.

Was this intentional? Can the copyright and license notice be removed from the generated output?

**Comment by xuri** [comment]
Thanks for your feedback, this is not intentional, I will remove copyright and license notice from the generated code.
