### ISSUE TITLE
Rust: "xs:string" being results in a "char" type.

### ISSUE THREAD

**Issue by abanduch** [xuri/xgen#22]
Thanks for the library, I am looking at using it for  Go project and its pretty useful.

Was comparing it with the Rust output, I noticed that a "xs:string" is turned into a char type since String is not in the Rust BuildinTypes pick list. I'd suggest for the time being that String is added here instead, while there may be other option more suited to different performance needs, String would be a good general use case start and not incorrect like char is.

However, this would need some additional logic on your end to map the types since https://github.com/xuri/xgen/blob/master/genRust.go#L152 is just doing a simple bool check.

**Comment by xuri** [comment]
Thanks for your suggestion, I have update it.
