### ISSUE TITLE
xsd:byte should be int8 instead of byte in Go

### ISSUE THREAD

**Issue by ArFe** [xuri/xgen#58]
When parsing the "xsd:byte" tag, it parses byte. Byte is unsigned in go, so it should be int8 (signed instead).

**Steps to reproduce the issue:**
1. Have an xsd with a byte tag
2. try to convert to struct

**Describe the results you received:**
struct with byte
**Describe the results you expected:**
struct with int8
**Output of `go version`:**
go version go1.18 linux/amd64
**xgen version or commit ID:**
98e2a901798bddb93c5e532c98afc1f5f139d47e

**Comment by mpkondrashin** [comment]
Not solved yet?
